name: PyBase - Continuous Integration

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
     - name: Install dependencies
       run: make _build 
     - name: Run Test
       run: make _test